name: Doxygen

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - lsplant/src/main/jni/include/**
      - README.md
      - docs/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Install doxygen
        run: sudo apt install -y doxygen
      - name: Generate doxygen
        run: doxygen docs/doxygen.cfg
      - name: Push to docs branch
        run: |
          cd docs/docs
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git init
          git add .
          git commit -m "docs"
          git push "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git" HEAD:docs -f
